---
title: "MSCA 31006 Time Series - Final Project - ... Model"
author: "Whitney Schreiber"
date: '2022-05-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load packages
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(zoo)
  library(xts)
  library(tseries)
  library(forecast)
  library(TSA)
  library(reshape2)
  library(naniar)
  library(lubridate)
})
```

# Import and process data 

```{r}
# import data
raw.df <- read.csv("city_temperature.csv")

# remove observations with year = 200, 201 or 2020 (only partial data), Day = 0 
wip.df <- raw.df %>% 
  filter(!Year %in% (200:201)) %>%
  filter(Day != 0)

# date data type
wip.df <- wip.df %>%
  mutate(Date = as.Date(with(wip.df,paste(Year,Month,Day,sep="-")),
                        "%Y-%m-%d")) %>%
  select(-c("Month","Day","Year"))

# number of days between the start and end date (inclusive)
n_days <- max(wip.df$Date) - min(wip.df$Date) + 1
```

Subset US cities

```{r}
# list of US cities of interest
CitiesOfInterest <- c("Chicago",
                      "Anchorage",
                      "Indianapolis",
                      "Kansas City",
                      "Las Vegas",
                      "Los Angeles",
                      "Miami Beach",
                      "Minneapolis St. Paul",
                      "New York City",
                      "Phoenix",
                      "Raleigh Durham",
                      "San Antonio")

# subset US cities of interest 
df.usa <- wip.df %>% dplyr::filter((Country=="US") 
                                     & (City %in% CitiesOfInterest) 
                                     & (State!="Additional Territories")) %>%
  select(-c("Region", "Country", "State")) # drop redundant columns

# reshape data set, one column per city
df_melt <- melt(df.usa, id.vars = c("Date","City"))
df.usa2 <- dcast(df_melt, Date ~ City)

# update values where `AvgTemperature` = -99 by forward filling 
df.usa2 <- df.usa2 %>% 
  naniar::replace_with_na_all(condition = ~.x == -99) %>%
  na.locf(fromLast = FALSE)
```

## Univariate Time Series: Daily, Weekly, Monthly Avg Temp in Chicago

*Create Test and Train Splits*

-   Train : 1995-01-01 - 2019-12-31
-   Test : 2020-01-01 - 2020-05-13

```{r}
# select Chicago
df <- df.usa2 %>% select(c("Date","Chicago")) %>% rename(AvgTemp = "Chicago")
```

```{r}
# ts of daily avg temp
ts.d <- df %>% select(-c("Date")) %>% ts(start=c(1995,1), frequency=365)
# split test and train
train.d <- window(ts.d, end=c(2019,365))  ;  autoplot(train.d)
test.d <- window(ts.d, start=c(2020,1))   ;  autoplot(test.d)
# check length
length(ts.d) == n_days
length(ts.d) == length(train.d) + length(test.d)
```

```{r}
# weekly avg temp
ts.w <- df %>%
  # group by week, use week start date
  group_by(WeekStart = lubridate::floor_date(df$Date,unit="week")) %>%
  # calculate avg
  summarize(AvgTemp = mean(AvgTemp) %>% round(2)) %>% 
  # drop "WeekStart" date before converting to ts
  select(-c("WeekStart")) %>%
  # convert to time series object
  ts(start=c(1995,1), deltat=1/52)
# split test and train
train.w <- window(ts.w, start=c(1995,1), end=c(2019,52))  ;  autoplot(train.w)
test.w <- window(ts.w, start=c(2020,1))  ;  autoplot(test.w)
# check length
length(ts.w) == length(train.w) + length(test.w)
```

```{r}
# monthly avg temp
ts.m <- df %>%
  # group by YearMonth
  group_by(YearMonth = as.yearmon(Date)) %>%
  # calculate avg
  summarize(AvgTemp = mean(AvgTemp) %>% round(2)) %>% 
  # drop "YearMonth" date before converting to ts
  select(-c("YearMonth")) %>%
  # convert to time series object
  ts(start=c(1995,1), frequency=12)
# split test and train
train.m <- window(ts.m, end=c(2019,12))  ;  autoplot(train.m)
test.m <- window(ts.m, start=c(2020,1))  ;  autoplot(test.m)
# check length
length(ts.m) == length(train.m) + length(test.m)
```

# Model



