---
title: "MScA 31006 Final Project EDA"
author: "Anna Auersperg"
date: "`r Sys.Date()`"
output: html_document
---


```{r setup, include=FALSE}
packages <- c("tidyverse","reshape2","gdata","xts","forecast","lubridate","tseries","fpp","tsibble","feasts")
lapply(packages, require, character.only = TRUE)
options(repr.plot.width = 20, repr.plot.height = 8)
```

# Load Data
*Daily temperature of major cities*
https://www.kaggle.com/datasets/sudalairajkumar/daily-temperature-of-major-cities?resource=download
+ Region
+ Country
+ State
+ City
+ Month
+ Day
+ Year
+ AvgTemperature
```{r}
df <-read.csv("city_temperature.csv")
head(df)
str(df)

summary(df$AvgTemperature)
apply(df %>% select(-c("AvgTemperature")),2,unique)
apply(df %>% select(-c("AvgTemperature")),2,function(x) length(unique(x)))
```
## Data Preprocessing
```{r}
#remove observations with year = 200, 201 or 2020 (only partial data), Day = 0 
df <- df %>% 
  filter(!Year %in% (200:201)) %>%
  filter(Year < 2020) %>%
  filter(Day != 0)
```
# Univariate distribution
```{r}
df %>% distinct(Country)
df %>% 
  filter(AvgTemperature>0) %>%
  ggplot(aes(AvgTemperature)) +
  geom_density(aes(fill=Region), alpha=1/4)

df %>%
  filter(AvgTemperature>0)%>%
  ggplot(aes(Region,AvgTemperature)) +
  geom_violin(aes(fill=Region),alpha=1/4)
```

# Avg Temperature per Year
```{r}
df %>% filter(., !is.na(AvgTemperature)) %>%
  group_by(Region,Year) %>%
  summarise(Temp = mean(AvgTemperature)) %>%
  ggplot(aes(x = Year, y = Temp,color=Region)) + 
  geom_line() 
```

# Cities with Highest Avg Temp
```{r}
hot_cities <- df %>%
  filter(., !is.na(AvgTemperature)) %>%
  group_by(City) %>%
  summarise(avg_temp = mean(AvgTemperature, na.rm = TRUE)) %>%
  ungroup() %>%
  top_n(n = 10, wt = avg_temp) %>% arrange(-avg_temp)
hot_cities
```

# Focus on 50 US States
```{r}
df.usa <- subset(df, (Country == 'US' & State != 'Additional Territories'))
df.usa$City <- paste(df.usa$City,df.usa$State,sep=", ")
#drop region and country columns 
df.usa <- df.usa[, !(names(df.usa) %in% c('Country','Region'))]
df.usa[is.na(df.usa)]
```
### Convert to Time series 
```{r}
#convert date 
df.usa$date <- as.Date(with(df.usa, paste(Year, Month, Day, sep="-")),"%Y-%m-%d")
df.usa <- df.usa[, !(names(df.usa) %in% c('Year','Month','Day'))]

# store start and end date s.t. seqence can be referenced to create a smooth series 
start.dt <- min(df.usa$date)
end.dt <- max(df.usa$date)
all.dts <- seq(start.dt, end.dt,by = 1)

df.usa <- df.usa %>% distinct()
df.usa$City %>% unique()

#combine DC and District of Columbia
all(df.usa[which(df.usa$City=="Washington DC, Maryland"),"AvgTemperature"] ==
    df.usa[which(df.usa$City=="Washington, District of Columbia"),"AvgTemperature"])

df.usa <- df.usa %>% filter(City != "Washington DC, Maryland")
df.usa %>% filter(City == "Washington, District of Columbia") %>% count(City)

# remove cities with incomplete data 
countCity <- df.usa %>% count(City) 
countCity %>% filter(countCity$n != (end.dt - start.dt + 1))
```
Forward fill where temp = -99
```{r}
#lowest temperature recorded on earth is -128.6 F in Antarctica, based on the fact this appears in temperate climates I will remove all of these 
df.usa %>% filter(AvgTemperature <= -80) %>% count(City)
df.usa <- df.usa %>% mutate(AvgTemperature = na_if(AvgTemperature, -99)) %>% 
  mutate(., AvgTemperature = na.locf(AvgTemperature, fromLast = FALSE))
df.usa
```

```{r}
mean.usa <- df.usa %>%
  group_by(Year_Month = yearmonth(date)) %>% 
  summarise(AvgTemp = round(mean(AvgTemperature), 2))
mean.usa
```

```{r}
month.delta <- function(m){
  mnthly.mean <-mean.usa %>% filter(month(Year_Month) == m)
  delta <- round(mnthly.mean$AvgTemp - mnthly.mean$AvgTemp[1],2)
  
  ggplot(data = mnthly.mean) +
    geom_point(aes(x = year(Year_Month), y = delta))  +
    geom_line(aes(x = year(Year_Month), y = delta)) + 
    geom_smooth(aes(x = year(Year_Month), y = delta)) + 
    scale_x_continuous(breaks = seq(1995, 2020, by = 1)) + 
    scale_y_continuous(breaks = seq(-6, 6, by = 0.5)) +
    geom_line(aes(x = year(Year_Month), y = delta[1]), colour = "red", linetype = "dashed", size = 0.8) +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) + 
    labs(title = paste("Variation during the month of", month.abb[m]), 
      y = expression(paste(Delta)), 
      x = "Years")
}

lapply(unique(month(mean.usa$Year_Month)),month.delta)
```

### Change in extreme temps 
clear seasonality 
```{r}
extreme <- df.usa %>% group_by(Year_Month = yearmonth(date)) %>%
  summarise(AvgTemp = round(mean(AvgTemperature), 2), 
            Max = max(AvgTemperature), 
            Min = min(AvgTemperature))

ggplot(extreme) +
  geom_line(aes(x = Year_Month, y = Min), col = "Blue") + 
  geom_line(aes(x = Year_Month, y = Max), col = 2) +
  labs(x ="Date", y = "Min Max") 

extreme.mnthly <- function(m){
  minimax <- extreme %>% filter(month(Year_Month) == m)
  ggplot(data = minimax) + 
    geom_line(aes(x = year(Year_Month), y = Min), col = "Blue") +
    geom_point(aes(x = year(Year_Month), y = Min), col = "Blue") +
    geom_smooth(aes(x = year(Year_Month), y = Min), col = "Blue") + 
    geom_line(aes(x = year(Year_Month), y = Max), col = 2) +
    geom_point(aes(x = year(Year_Month), y = Max), col = 2) +
    geom_smooth(aes(x = year(Year_Month), y = Max), col = 2) +
    scale_x_continuous(breaks = seq(1995, 2019, by = 1)) +
    labs(title = paste("Minima and Maxima of ",month.abb[m]), x = "Year", y = "Min (blue)  Max (red)")  + 
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5))
}

lapply(unique(month(mean.usa$Year_Month)),extreme.mnthly)
```

