---
title: "MSCA 31006 Time Series - Final Project - ARIMA Model (WIP)"
author: "Whitney Schreiber"
date: '2022-05-26'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load packages
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(zoo)
  library(xts)
  library(tseries)
  library(forecast)
  library(TSA)
  library(reshape2)
  library(naniar)
  library(lubridate)
})
```

# Import and process data 

```{r}
# import data
raw_df <- read.csv("city_temperature.csv")

# remove observations with year = 200, 201 or 2020 (only partial data), Day = 0 
wip_df <- raw_df %>% 
  filter(!Year %in% (200:201)) %>%
  filter(Day != 0)

# date data type
wip_df <- wip_df %>%
  mutate(Date = as.Date(with(wip_df,paste(Year,Month,Day,sep="-")),
                        "%Y-%m-%d")) %>%
  select(-c("Month","Day","Year"))

# number of days between the start and end date (inclusive)
n_days <- max(wip_df$Date) - min(wip_df$Date) + 1
```

Subset US cities

```{r}
# list of US cities of interest
CitiesOfInterest <- c("Chicago",
                      "Anchorage",
                      "Denver",
                      "Indianapolis",
                      "Kansas City",
                      "Las Vegas",
                      "Los Angeles",
                      "Miami Beach",
                      "Minneapolis St. Paul",
                      "New York City",
                      "Phoenix",
                      "Raleigh Durham",
                      "San Antonio")

# subset US cities of interest 
dfUS.wip <- wip_df %>% dplyr::filter((Country=="US") 
                                     & (City %in% CitiesOfInterest) 
                                     & (State!="Additional Territories")) %>%
  select(-c("Region", "Country")) # drop redundant columns

# Reshape data set, one column per city
df_melt <- melt(dfUS.wip, id.vars = c("Date","City","State"))
dfUS <- dcast(df_melt, Date ~ City)

# Update values where `AvgTemperature` = -99 by forward filling 
dfUS <- dfUS %>% naniar::replace_with_na_all(condition = ~.x == -99)
dfUS <- na.locf(na.locf(dfUS), fromLast = FALSE)
```

## Univariate Time Series: Daily, Weekly, Monthly Avg Temp in Chicago

### Create Test and Train Splits 

- Train : 1995-02-07 - 2019-12-31
- Test  : 2020-01-01 - 2020-05-13

```{r}
# daily average temperature
df <- dfUS %>% select(c("Date","Chicago")) %>% rename(AvgTemp = "Chicago")
# create test/train splits
dfTrain <- df %>% dplyr::filter(Date <= "2019-12-31")
dfTest <- df %>% dplyr::filter(Date >= "2020-01-01")
# create xts objects
tsTrain <- xts(dfTrain[,!names(dfTrain) %in% c("Date")], order.by=dfTrain$Date)
tsTest <- xts(dfTest[,!names(dfTest) %in% c("Date")], order.by=dfTest$Date)
```

```{r}
# weekly average temperature (week starting Monday)
dfW <- df %>%
  group_by(WeekStart = floor_date(df$Date, unit="week")) %>%
  summarize(AvgTemp = mean(AvgTemp) %>% round(2))
# create test/train splits
dfWTrain <- dfW %>% dplyr::filter(WeekStart <= "2019-12-31")
dfWTest <- dfW %>% dplyr::filter(WeekStart >= "2020-01-01")
# create xts objects
tsWTrain <- xts(dfWTrain[,!names(dfWTrain) %in% c("WeekStart")], order.by=dfWTrain$WeekStart)
tsWTest <- xts(dfWTest[,!names(dfWTest) %in% c("WeekStart")], order.by=dfWTest$WeekStart)
```

```{r}
# monthly average temperature
dfM <- df %>%
  group_by(YearMonth = as.yearmon(Date)) %>% 
  summarize(AvgTemp = mean(AvgTemp) %>% round(2))
# create test/train splits
dfMTrain <- dfM %>% dplyr::filter(YearMonth <= "2019-12-31")
dfMTest <- dfM %>% dplyr::filter(YearMonth >= "2020-01-01")
# create xts objects
tsMTrain <- xts(dfMTrain[,!names(dfMTrain) %in% c("YearMonth")], order.by=dfMTrain$YearMonth)
tsMTest <- xts(dfMTest[,!names(dfMTest) %in% c("YearMonth")], order.by=dfMTest$YearMonth)
```



