---
title: "MSCA 31006 Time Series - Final Project - Holt Winters"
author: "Anna Auersperg"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load packages
packages <- c("tidyverse","reshape2","xts","forecast","lubridate","tseries","fpp","tsibble","feasts","TSA","naniar","lubridate")
suppressPackageStartupMessages(lapply(packages, require, character.only = TRUE))
```

# Import and process data

```{r}
# import data
raw.df <- read.csv("city_temperature.csv")
# remove observations with year = 200, 201 or 2020 (only partial data), Day = 0 
wip.df <- raw.df %>% 
  filter(!Year %in% (200:201)) %>%
  filter(Day != 0)
# date data type
wip.df <- wip.df %>%
  mutate(Date = as.Date(with(wip.df,paste(Year,Month,Day,sep="-")),
                        "%Y-%m-%d")) %>%
  select(-c("Month","Day","Year"))
# number of days between the start and end date (inclusive)
n_days <- max(wip.df$Date) - min(wip.df$Date) + 1
```

Subset US cities

```{r}
# list of US cities of interest
CitiesOfInterest <- c("Chicago",
                      "Lincoln",
                      "Eugene",
                      "Kansas City",
                      "Las Vegas",
                      "Los Angeles",
                      "Minneapolis St. Paul",
                      "Phoenix",
                      "San Antonio",
                      "Salt Lake City",
                      "Cheyenne",
                      "Tulsa")
# subset US cities of interest 
df.usa <- wip.df %>% dplyr::filter((Country=="US") 
                                    & (City %in% CitiesOfInterest) 
                                    & (State!="Additional Territories")) %>%
  select(-c("Region", "Country", "State")) # drop redundant columns


# reshape data set, one column per city
df_melt <- melt(df.usa, id.vars = c("Date","City"))
df.usa2 <- dcast(df_melt, Date ~ City)
# update values where `AvgTemperature` = -99 by forward filling 
df.usa2 <- df.usa2 %>% 
  naniar::replace_with_na_all(condition = ~.x == -99) %>%
  na.locf(fromLast = FALSE)
nrow(df.usa2) == n_days

df <- df.usa2 %>% select(c("Date","Chicago")) %>% rename(AvgTemp = "Chicago")



head(df)
str(df)
```
## Univariate Time Series: Daily, Weekly, Monthly Avg Temp in Chicago
```{r}
generateTS <- function(freq){
  if(freq == 'week'){
      ts <- df %>% group_by(WeekStart = lubridate::floor_date(df$Date,unit="week")) %>%
        summarize(AvgTemp = mean(AvgTemp) %>% round(2)) %>% 
        select(-c("WeekStart")) %>% ts(start=c(1995,1), deltat=1/52)
  }
  if(freq == 'month'){
    ts <- df %>% 
      group_by(YearMonth = as.yearmon(Date)) %>%
      summarize(AvgTemp = mean(AvgTemp) %>% round(2)) %>% 
      select(-c("YearMonth")) %>% ts(start=c(1995,1), frequency=12)
  }
  else{
    ts <-  df %>% select(-c("Date")) %>% ts(start=c(1995,1), frequency=365)
  }
  ts 
}
frequencies <- c("day","week","month")
lapply(frequencies, function(x){ 
  ts <- generateTS(x)
  decompose(ts) %>% plot()
})
```

*Create Test and Train Splits*

-   Train : 1995-01-01 - 2019-12-31
-   Test : 2020-01-01 - 2020-05-13

```{r}
train.dat <- function(freq){
  ts <- generateTS(freq)
  if(freq == 'week'){
    window(ts, start=c(1995,1), end=c(2019,52))
  }
  if(freq == 'month'){
    window(ts, end=c(2019,12))
  }
  else{window(ts, end=c(2019,365))}
}

lapply(frequencies, function(x){
  ts <- generateTS(x)
  train <- train.dat(x)
  test <- window(ts, start=c(2020,1))
  length(ts) == (length(train) + length(test))
})
```

# Holt Winters
### Seasonal Decomposition 

```{r}
fit.HW <- function(freq){
  train <- train.dat(freq)
  hw.add <- HoltWinters(train)
  hw.mult <- HoltWinters(train, seasonal="multiplicative")
  plot(train, ylab="Average Temperature", xlim=c(1995,2020), main="Additive vs. Multiplicative Seasonality")
  lines(hw.add$fitted[,1],  col="blue")
  lines(hw.mult$fitted[,1], col="red")
}
lapply(frequencies, fit.HW)
```


```{r}
get.HW.params <- function(mod){
  data.frame(alpha = round(mod$alpha,5),
        beta = round(mod$beta,5),
        gamma = round(mod$gamma,5), row.names = mod$seasonal)
}
```

### Additive
```{r}
ts <- generateTS("week")
test <- window(ts, start=c(2020,1))
train <- train.dat("week")
results <-  data.frame(Date = seq(from = min(df$Date), by = "week", length.out = length(test)),
                    Observed = as.numeric(test))

hw.1 <- HoltWinters(train)
hw.1.fc <- forecast(hw.1,h=length(test),level=c(80,95))
results$HW.Additive <- hw.1.fc$mean

plot(hw.1.fc, xlim=c(1995, 2020), main="Additive Forecasts From HW")
lines(hw.1.fc$fitted, lty=2, col="purple")
```
#### Analyze Residuals
```{r}
checkresiduals(hw.1)
resid <- hw.1.fc$residuals
print(Box.test(resid,type="Ljung-Box"))
```

Square of Residuals 
```{r}
hw.1 %>% summary
```
### Multiplicative
```{r}
hw.2 <- HoltWinters(ts, seasonal = "multiplicative")
hw.2.fc <- forecast(hw.2,h=52)
checkresiduals(hw.2)
#results$HW.Multiplicative <- hw.2.fc$mean

#EvaluateModel(hw.2.fc)
```

### Results
```{r}
get.HW.params(hw.1)

results
round(accuracy(hw.1.fc,test), digits=4)
```





